deploy:
  runs-on: windows-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
  
  
 
steps:
    
   
- name: Download artifact from build job
      
  
uses: actions/download-artifact@v3
      
    
with:
        
      
name: ASP-app
    
    name: Deploy to Azure Web App
      id: deploy-to-webapp
      
     
uses: azure/webapps-deploy@v2
      with:
        app-name: 'pizzaslunches'
        
       
slot-name: 'Production'
        package: .
        
    
publish-profile: "${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_63FA55290CD5473EB8BA67791B84BA30 }}"
